# Generated by Django 4.0.1 on 2022-02-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_codregistro_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
